import { NextRequest, NextResponse } from "next/server";
import schema from "./schema";
import prisma from "@/prisma/client";


export async function GET(request: NextRequest) {
  // Get w/ Prisma
  const products = await prisma.product.findMany();

  return NextResponse.json(products);
}

// Create product
export async function POST(request : NextRequest) {
  const body = await request.json();
  const validation = schema.safeParse(body);

  //Zod validation
  if(!validation.success) 
    return NextResponse.json(validation.error.errors, { status : 400})
  
  //Create product
  const newProduct = await prisma.product.create({
    data: {
      name: body.name,
      price: body.price
    }
  })

  // Id would be generated by DB
  return NextResponse.json(newProduct, { status : 201 })
}

